remote-control:
    control-enable: yes
    server-cert-file: "/opt/unbound-dashboard/certs/192.168.3.111/unbound_server.pem"
    control-key-file: "/opt/unbound-dashboard/certs/192.168.3.111/unbound_control.key"
    control-cert-file: "/opt/unbound-dashboard/certs/192.168.3.111/unbound_control.pem"
